name: pipeline

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  pipeline:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install build

    - name: Lint
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Checkout github repo
      uses: actions/checkout@v2
      with:
        ref: 'main'
        token: "${{ secrets.REPO_DATA_TOKEN }}"

    - name: Run python workflow
      run: |
        export PYTHONPATH="$PYTHONPATH:./src"
        python workflows/pipeline.py
        

    - name: Push to github repo
      run: |
        git config --global user.email "${{ secrets.GIT_USER_EMAIL }}"
        git config --global user.name "${{ secrets.GIT_USER_NAME }}"
        
        echo "* $(date)" >> updates.txt

        git pull origin main
        git add .
        git commit -m "pipeline $(date)"
        git push origin main
